name: Deploy to Snowflake

on:
  push:
    branches:
      - prod
    paths:
      - "src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    env:
      ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
      USER_NAME: ${{ vars.SNOWFLAKE_USER }}
      PASSWORD: ${{ secrets.SNOWFLAKE_PWD }}
      ROLE: ${{ vars.SNOWFLAKE_ROLE }}
      DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
      SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}
      WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install snowdev using pip
      - name: Install snowdev
        run: |
          python -m pip install --upgrade pip
          pip install snowdev

      - name: Deploy to Snowflake
        run: |
          cd src
          for dir in */; do
            component_type=${dir%/}
            case $component_type in
              task)
                snowdev deploy --task $dir || continue
                ;;
              streamlit)
                snowdev deploy --streamlit $dir || continue
                ;;
              udf)
                snowdev deploy --udf $dir || continue
                ;;
              sproc)
                snowdev deploy --sproc $dir || continue
                ;;
            esac
          done

        continue-on-error: true
